language: python

python: 3.6

# don't clone more than necessary
git:
    depth: 1

install:
    - pip install -r requirements.txt

script:
    - coverage run stats_test.py

# create a coverage report on Codecov.io
after_script:
    - bash < (curl -s https://codecov.io/bash)
