language: python

python: 3.6

# don't clone more than necessary
git:
    depth: 1

install:
    - pip install -r requirements.txt

script:
    - flake8 stats.py
    - coverage run stats_test.py

# create a coverage report on Coveralls.io
after_script:
    - coveralls
